# SSH Authentication
ssh_auth_type=Password
ssh_key_loaded=False
ssh_key_path=
ssh_key_encrypted=False
ssh_key_type=RSA

# Server Address
server_hostname=
server_username=

# Virtual Machine Paths
local_vms_path=
server_vms_path=
vm_ext=
vm_hashfile_path=
