# SSH Authentication
ssh_auth_method=0
ssh_key_type=RSA
ssh_timeout=10

# Server Address
server_hostname=
server_username=

# Virtual Machine Paths
local_vms_path=
server_vms_path=
vm_ext=
vm_hashfile_path=
