# SSH Authentication
ssh_auth_type=Password
ssh_key_path=
ssh_key_type=RSA
ssh_key_encrypted=False
save_ssh_password=False
save_ssh_key_password=False

# Server Address
server_hostname=
server_username=

# Virtual Machine Paths
local_vms_path=
server_vms_path=
vm_ext=
search_depth=5
